### ISSUE TITLE
Setup Travis CI for deploying binaries

### ISSUE THREAD

**Issue by Symbian9** [rodlie/cyan#10]
Compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:

- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

### TODO

1. https://github.com/appimage/appimagekit
1.1 https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/probonopd/uploadtool

**PLEASE NOTE:** For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) **prior to merging this**, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by rodlie** [comment]
Sorry for not responding, for some reason this repo was unwatched in my account...

I prefer to build static files on Linux, appimage just complicates thing for me.

**Comment by rodlie** [comment]
So, your post triggered me to drop building binaries on my own server.

I have currently added full CI for Win64 (I started with the most challenging build, osx/linux is trivial compared). Travis will now build and unit test Win64, and on pull request upload the binary to https://transfer.sh and add a comment to the pull request with the URL.

I will add support for snapshots and releases (on SourceForge, since they have much better file management than Github), and of course add linux and osx support.

An example pull request with build can be found here: https://github.com/rodlie/cyan/pull/14

**Comment by rodlie** [comment]
Linux is done, I have also fixed the release stuff.

next up is osx.

**Comment by rodlie** [comment]
Mac is now done.

The release stuff should work in theory, but I need to do a test on that. 

This should conclude this issue.
