### ISSUE TITLE
[v1.2 Win64] Cyan crashing when CMYK .tif opened

### ISSUE THREAD

**Issue by SimonLandmine** [rodlie/cyan#100]
Running Cyan v1.2.2 on Windows 10.

I have a CMYK .tif that I converted for print from a .png using Cyan 1.2.2.

However, if I open the .tif using Cyan, Cyan crashes and closes. This occurs whether I a) drag-and-drop the .tif, b) use the File menu from Cyan, or even c) use the 'Open With' right-click option from the file.

It's not an especially large file (for a .tif) - only 2.4 MB - is there a file size limitation for Cyan?

**Comment by rodlie** [comment]
I will need to check this after work today.

**Comment by SimonLandmine** [comment]
Cheers. Let me know if you need a file as a sample.

**Comment by rodlie** [comment]
btw, does this work better? https://github.com/rodlie/cyan/files/7231632/Cyan-202109261718-Windows.zip

1.2.2 has issues with some TIF files.

**Comment by rodlie** [comment]
But, running the Windows binary on Linux through WINE works .... odd.

**Comment by rodlie** [comment]
It's the CMYK built-in profile (ISO Coated) that fails to read, I do not know why. Please use a different profile (it's a failsafe, should not be used anyway).

Good profiles: https://web.archive.org/web/20160322191318/http://download.adobe.com/pub/adobe/iccprofiles/win/AdobeICCProfilesCS4Win_end-user.zip 

I recommend USWebCoatedSWOP.icc, or even better the actual profile the printer will use ;)

**Comment by SimonLandmine** [comment]
Thanks! I was running it as a test while waiting for the printer to get back to me with the profile they actually use, because it wasn't listed on their website. Fortunately, the other printer, for the other thing I need to submit, helpfully specifies the profile they use.

(It's not very failsafe if it breaks! :D Unless it's just there to ensure that an array has at least one member.)

**Comment by SimonLandmine** [comment]
Thanks for all of your help!
