### ISSUE TITLE
Cyan 1.2.2 not appearing in GIMP 2.10.24 (Pop OS and Elementary)

### ISSUE THREAD

**Issue by dzacca** [rodlie/cyan#105]
Hi, I installed Cyan 1.2.2 and configured it with the default color profiles.

The plug-in is correctly installed in my user directory, ~/.config/GIMP/2.10/plug-ins, as cyan,py, but Cyan does not appear in GIMP's menu.

This happens in both Elementary 6 and in Pop OS with both the flatpack and the .deb versions of GIMP. I'm currently on the .deb installation on Pop OS. Cyan as a standalone application works correctly.

**Comment by Zeioth** [comment]
Same issue here. It works fine as standalone program.

**Comment by rodlie** [comment]
Does other Python plugins work in GIMP?

**Comment by rodlie** [comment]
Just tested latest version of GIMP on Windows and Linux, Cyan 1.2.2 binary works fine here.

The problem is not on my end.
