### ISSUE TITLE
Dialgue with no text and an error message appears when exporting an image from GIMP

### ISSUE THREAD

**Issue by makotonium** [rodlie/cyan#108]
Environment:
Mac OS Monterey V 12.2.1
GIMP 2.10.30
Cyan 1.2.2

Problem:
Whenever I export an image from GIMP via Cyan > Export Image, I got a blank dialog and then an unknown field tag error. Not sure why it started happening. I can still export an image, select a CYMK profile and save the image so it appears to be that Cyan is working fine, but not 100% sure.

<img width="1070" alt="Screen Shot 2022-03-22 at 7 20 05 AM" src="https://user-images.githubusercontent.com/21201009/159515503-9df885ea-3aa2-41e8-9e51-602ae86f7cc6.png">

<img width="1065" alt="Screen Shot 2022-03-22 at 7 20 23 AM" src="https://user-images.githubusercontent.com/21201009/159515589-b85d5c38-b286-43d6-985b-22989a95c531.png">

Steps to Reproduce:
1. Open an image in GIMP
2. Select Cyan > Export Image

Comment:
Please let me know if you need further help on reproducing. Thanks for making Cyan.

**Comment by rodlie** [comment]
Thanks for the bug report, this should be fixed in 1.2.3.

But I didn't make a macOS binary for 1.2.3, as I wasn't sure I had any macOS users (left). I will make a macOS binary today or tomorrow.

**Comment by makotonium** [comment]
Thank you @rodlie! 🙏 Much appreciated!

I recently found your plugin through someone's blog article. I'm curious, is there a story behind why there is low number of Cyan users on macOS?

**Comment by rodlie** [comment]
Sorry for the late reply, getting the macOS port up-to-date took longer than expected. Also found a bug and will need to do a 1.2.4 release today.

Please test this: 
[Cyan-1.2.4-macOS-x86_64.dmg.zip](https://github.com/rodlie/cyan/files/8344398/Cyan-1.2.4-macOS-x86_64.dmg.zip)

> I'm curious, is there a story behind why there is low number of Cyan users on macOS?

No, just based on download numbers.

**Comment by rodlie** [comment]
fixed in 1.2.4, so close.

If you still have issues feel free to reopen this issue.
