### ISSUE TITLE
Does not work correctly if built against ImageMagick7: `Cyan: no decode delegate for this image format `' @ error/constitute.c/ReadImage/581`

### ISSUE THREAD

**Issue by barracuda156** [rodlie/cyan#116]
While it builds fine with ImageMagick7, it fails to open images then.
ImageMagick6 works fine with everything else identical.

**Comment by rodlie** [comment]
That error message just says that IM can't read something, check that IM7 supports what you want to read. Run the tests in Cyan after build, if they fail then Cyan is built against something broken.

Also note that I do not support IM7 (I wasted Cyan v2 on IM7 just to find out IM7 is very broken in some places).

**Comment by barracuda156** [comment]
@rodlie Thanks for clarification. Then there is no point in using IM7 with it, we are good with IM6.
