### ISSUE TITLE
How to use this in Gimp 2.10 on a Linux Machine ?

### ISSUE THREAD

**Issue by mujeebcpy** [rodlie/cyan#69]
i cant find any documentation on how to use this plugin on Gimp.

**Comment by mujeebcpy** [comment]
first of all i dont have a .gimp directory. plugins located at ~/.config/GIMP/2.10/plug-ins directory. there is no cyan.py i got an executable file with thirdparty libraries. no py module in it. 
![image](https://user-images.githubusercontent.com/24728052/64843219-23d67480-d622-11e9-9d28-89f23cbe625b.png)

**Comment by mujeebcpy** [comment]
tried both in version 1.2 and 1.2.1, same result

**Comment by rodlie** [comment]
Cyan creates the plugin when needed. Since Gimp on Linux changed the config location you will need to do a workaround ....

Create the folder ~/.gimp-2.10 and start Cyan. Cyan will create a plugin in that folder. Copy/move it to where you want.

**Comment by rodlie** [comment]
I will do a release (1.2.2) to fix the Linux issue within Monday.

**Comment by mujeebcpy** [comment]
okey. Thank You

**Comment by rodlie** [comment]
https://github.com/rodlie/cyan/releases/tag/1.2.2-rc1

Should fix the GIMP issue, please re-open if that is not the case.
