### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by hudefect** [rodlie/cyan#86]
Hello, 

I found this software while trying to load a a CMYK PSD file in GIMP. 

This is an awesome tool, keep up with the good work. 

**Some background on what I am trying to do:**

I am trying to load a PSD file in GIMP so I can edit the text in it and export the final image to use in my website. 

The file I am trying to edit is about 12 MB. 

I am running Windows 10 with 32 GB RAM and I have installed GIMP 2.10.14 and ImageMagick-7.0.10 x64. 

I saw in the Cyan documentation that I should be using ImageMagick 7.0.8 but I could not find this version to download. Not sure if this is what might be causing the problem. If you now where I can get the correct version I can try again with it.

**The issue:**

When I try to load the file in Cyan I get the error message below:

![image](https://user-images.githubusercontent.com/67909668/91003540-3e5af100-e5da-11ea-9dc1-15b6cfb7853a.png)

After ignoring it for a couple times a window opens showing the image has 10 layers. 

After ignoring the message several more times, the image finally opens. 

I can then convert it to RGB and load it in GIMP, but everything is loaded into the same layer and I cannot edit the text....

I tried increasing the memory limits in Image Magick policy file to 4 and 6 GiB but it did not make any difference.

**Conclusion:**

I am not really sure what is going on, my guess is that the issue can be caused by (1) the incorrect Image Magick version, (2) some additional setup or configuration that I am missing or (3) some bug with Cyan or Image Magick.

Appreciate if someone can point me in the right direction to get this sorted.

Thanks!

**Comment by rodlie** [comment]
Hi,

Thanks for the bug report. This is probably a memory limit issue with the included ImageMagick. I will do a rebuild of the Windows version as soon as possible.

**Comment by rodlie** [comment]
I added an option for memory limit (file=>preferences=>memory limit), there you can set the maximum amount of memory used by ImageMagick, 1.2.2 was set to 2GB without any way to expand it (not really usable with Q32).

I will trigger a test build soon.

**Comment by rodlie** [comment]
Please test: https://github.com/rodlie/cyan/releases/tag/continuous-1.2

**Comment by hudefect** [comment]
Thanks for the prompt reply and action.

I have tested and it works great once I set the memory limit to maximum!

Apologies for my delay on replying - got carried away with other projects.
