### ISSUE TITLE
gimp extension doesn't work

### ISSUE THREAD

**Issue by RivinHD** [rodlie/cyan#97]
When I click the Extension buttons "Export Image" and "Import Image" in Gimp, the Cyan doesn't get launched.

I get it to work by changing
```
child = subprocess.Popen( cyanbin + " " + tempfilename, stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True )
...
child = subprocess.Popen( cyanbin + " -o " + tempfilename, stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True )
```
to 
```
child = subprocess.Popen( [cyanbin, tempfilename], stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True )
...
child = subprocess.Popen( [cyanbin, "-o", tempfilename], stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True )
```

Gimp Version: 2.10.24
Windows 10 Version 20H2

**Comment by rodlie** [comment]
I don't have time to look at Cyan this week, but I can do stuff next week.

Btw, feel free to do a PR (against branch 1.2 or 1.3).

**Comment by RivinHD** [comment]
ok, I will do a PR.

Thx for the reply, don't stress yourself.

**Comment by SimonLandmine** [comment]
It's not working for me either - I was wondering if I needed to install it somewhere specific for GIMP to be able to open it? In the meantime, it works as a standalone converter.

**Comment by rodlie** [comment]
I will merge the PR and do a release as soon as possible.

**Comment by rodlie** [comment]
Famous last words :P Sorry for the delay, will do a 1.2.3 release by the end of this week. The main branch is not ready for a release yet.

**Comment by SimonLandmine** [comment]
Life happens! Thanks for all of your work!
