### ISSUE TITLE
msvcrt.dll bug

### ISSUE THREAD

**Issue by RabiesKit** [rodlie/cyan#99]
I keep getting the following message.
The procedure entry point_free_locale could not be located in the dynamic link library msvcrt.dll
It downloaded and everything just stopped. i have dozens of this all over the place.

thanks

Tim.

**Comment by rodlie** [comment]
Windows version?

**Comment by RabiesKit** [comment]
Hello Ole-André,


Hi there,
win 7 home premium. I5 12gb ram 24Tb hdd space.
Thanks,
Tim.

Saturday, September 25, 2021, 11:52:31 PM, you wrote:

> Windows version?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
Thanks for the information, it seems to be an issue with a third-party library (from ImageMagick) that causes this issue. I didn't catch this issue since I don't have access to Windows 7 anymore.

I will make a patch release as soon as possible. Sorry for the inconvenience.

**Comment by RabiesKit** [comment]
Hello Ole-André,

All because I have to convert some RGB images to cmyk for the printers. Some clown used a piece of shit called canva, swearing it was perfect and that I knew nothing.
Well anva is crap, only works rgb and A4.. fine for business cards,and laser printers, but not foe a proper (if small newspaper.. LOL

Thanks again.
 

Sunday, September 26, 2021, 12:05:16 AM, you wrote:

> Thanks for the information, it seems to be an issue with a third-party library (from ImageMagick) that causes this issue. I didn't catch this issue since I don't have access to Windows 7 anymore.
> I will make a patch release as soon as possible. Sorry for the inconvenience.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
That's why I made this app :)

I'm currently rebuilding the SDK, will post a build here when done (could take an hour or so).

**Comment by rodlie** [comment]
btw, an older version should work, try 1.2.1: https://github.com/rodlie/cyan/releases/tag/1.2.1

**Comment by RabiesKit** [comment]
Hello Ole-André,


Just in case, here is a link to a zip file.
https://www.bayislandnews.com.au/Done.zip
 
thanks again
 
Tim.

Sunday, September 26, 2021, 12:49:15 AM, you wrote:

> btw, an older version should work, try 1.2.1: https://github.com/rodlie/cyan/releases/tag/1.2.1
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by RabiesKit** [comment]
Hello Ole-André,

Hello Ole-André,
Hi Ole-André,
 
GIT keeps rejecting my emails as too large!
here is a link instead..
https://www.bayislandnews.com.au/Done.zip
 

By the way, github rejected my first email as too large, hopefully this one will work..
I am holding my breath, The first didn't work, because I didn't give it an output type (duh).
So I tried it again, using swop standard. it seemed to fail, until I put it into a scribus document!

There is dancing in the streets, the birds are singing, the bank just lowered our interest rate!

You, Sir are a miracle worker!!

Can I do a batch and fix the other 48 pages?

Well done.

With thanks and disbelief,
Tim.

My number is:
460 923 470
send me yours and I'll thank you in person.







Sunday, September 26, 2021, 12:49:15 AM, you wrote:

> btw, an older version should work, try 1.2.1: https://github.com/rodlie/cyan/releases/tag/1.2.1
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by RabiesKit** [comment]
hi Ole,
i am getting this message.
 
Cyan.exe: I:/DOTS2018/Editions/Spring 2021/print test/images/bayislandsDOT (2).tif: Null count for "Tag 34391" (type 1, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/569 
 
i can't seem to close the image, other than closing the program.
there was a window but I stupidly closed it and cannot open it again..
i went and told everyone i had a fix, now i am in trouble. One single fix was not enough it seems.

Thanks again,
Tim

Sunday, September 26, 2021, 12:49:15 AM, you wrote:

> btw, an older version should work, try 1.2.1: https://github.com/rodlie/cyan/releases/tag/1.2.1
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
Sorry for the late reply, there where several issues with the Windows build (I have not touched it since 2019).

Anyway, this binary should work:
[Cyan-202109261718-Windows.zip](https://github.com/rodlie/cyan/files/7231632/Cyan-202109261718-Windows.zip)

**Comment by RabiesKit** [comment]
Hello Ole-André,


all I see is input, output depth and source.There used to be a box with image details.
But I can't open choose anything or save,,

help! I attached a screen shot

Cheers,
Tim

Monday, September 27, 2021, 1:20:21 AM, you wrote:

> Sorry for the late reply, there where several issues with the Windows build (I have not touched it since 2019).
> Anyway, this binary should work:
> Cyan-202109261718-Windows.zip
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
I can't see any screenshot, I don't think you can attach anything to emails you send to github.

You can't resize the window?

**Comment by rodlie** [comment]
You can try to remove the settings in Windows.

Start ``regedit`` (windows key + R and type regedit) and go to ``HKEY_CURRENT_USER`` => ``Software``: and remove any "folder" named ``Cyan`` or ``FxArena``.

**Comment by RabiesKit** [comment]
Hello Ole-André,


well,that seemed to work. It is 2.30am here in Australia, I'll check things tomorrow.
Ant way of doing a batch file? I have hundreds to convert - just thought I'd ask.
Where are you in the world?

Niight.
Tim.

Monday, September 27, 2021, 1:51:56 AM, you wrote:

> You can try to remove the settings in Windows.
> Start regedit (windows key + R and type regedit) and go to HKEY_CURRENT_USER => Software: and remove any "folder" named Cyan or FxArena.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
Batch support has not been added yet, it's something I'm working on (but my spare time is limited, so not much has happened this year).

I'm in Norway (18:30 Sunday).

**Comment by rodlie** [comment]
I forgot that I made a simple batch converter at work a while back, it's used to convert images from whatever to sRGB. I did a simple modification so you can convert to anything (I only tested CMYK).

[fargerom-2.0.0-202109262022-697a191.zip](https://github.com/rodlie/cyan/files/7231998/fargerom-2.0.0-202109262022-697a191.zip)

It was originally Norwegian (fargerom = color space), so I replaced the text strings with English.

It's very simple, select a color profile then drop as many images you want onto the window of the app. May contains bugs ;)

**Comment by RabiesKit** [comment]
Hi Ole,
Worked brilliantly. Did 48 files in 10 minutes! Sent the resulting PDF (I use Scribus) to the printers, hope to hear back soon  :) But Scribus says it is CMYK now.

Thanks again.

By the way, I have been to Norway as a child. Kristiansand. In the 1960's. Beautiful beaches. Had a great time with a similar aged girl, I was about 6 years old.
I had my first taste of real yougurt, with cornflakes - yeech, I thought it was milk!



Monday, September 27, 2021, 4:34:37 AM, you wrote:

> I forgot that I made a simple batch converter at work a while back, it's used to convert images from whatever to sRGB. I did a simple modification so you can convert to anything (I only tested CMYK).
> fargerom-2.0.0-202109262022-697a191.zip
> It was originally Norwegian (fargerom = color space), so I replaced the text strings with English.
> It's very simple, select a color profile then drop as many images you want onto the window of the app. May contains bugs ;)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
Great :) I hope it works out ok.

**Comment by RabiesKit** [comment]
Hi Ole,
seems that if I leave it on unattejded, I have ro hop into the registry and remove thar entry. Just thought I'd let you know.

Cheers,
Tim.




Monday, September 27, 2021, 4:37:28 PM, you wrote:

> Great :) I hope it works out ok.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by RabiesKit** [comment]
Hi Ole,
I can't seem to get the same result consistently. ould you gie me a hint?
The top menu has input and output. Sometimes I can get the dropdown to work, sometimes not. I am guessing input has am RGB component, the output something different..

The bottom menu is similar, something RGB in the input something Fogra in the output?

I can't open or close new images, I have tried cntrl , exit, etc, there must be a way to start again without restarting all over again...

Thanks,

Tim.

Monday, September 27, 2021, 1:51:56 AM, you wrote:

> You can try to remove the settings in Windows.
> Start regedit (windows key + R and type regedit) and go to HKEY_CURRENT_USER => Software: and remove any "folder" named Cyan or FxArena.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.


-- 
Best regards,
Tim Barler

**Comment by rodlie** [comment]
* Input is the profile from your input image, if none then the "default" (from the bottom) is used.
* Output is the desired output colorspace/profile you want to convert to
